export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as Offer } from './Offer'
export { default as Products } from './Products'
export { default as CTA } from './CTA'
export { default as Footer } from './Footer'
export { default as FAQSection } from './FAQSection'
